// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Arg } from "./Arg";

export type Call = "Nular" | { "Unary": Arg } | { "Binary": [Arg, Arg] };
