// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Branch } from "./Branch";
import type { Locality } from "./Locality";
import type { Since } from "./Since";
import type { Syntax } from "./Syntax";

export type Command = { name: string, desc: string, alias?: Array<string>, multiplayer_note?: string | null, problem_notes?: Array<string>, groups: Array<string>, syntax: Array<Syntax>, argument_loc: Locality, effect_loc: Locality, server_exec?: boolean | null, since: Since, branch?: Branch | null, examples?: Array<string>, see_also?: Array<string>, };
