// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Since } from "./Since";

export type NumberEnumValue = { value: number, desc: string | null, since: Since | null, };
