// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Since } from "./Since";
import type { Value } from "./Value";

export type OneOfValue = { type: Value, desc: string | null, since: Since | null, };
