// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Since } from "./Since";
import type { Value } from "./Value";

export type ParamItem = { name: string, desc?: string | null, type: Value, optional?: boolean, default?: string | null, since?: Since | null, };
