// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamItem } from "./ParamItem";

export type Param = { "Item": ParamItem } | { "Array": Array<Param> } | { "Infinite": Array<Param> };
