// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Version } from "./Version";

export type Since = { ofp?: Version | null, ofpe?: Version | null, arma1?: Version | null, arma2?: Version | null, arma2oa?: Version | null, tkoh?: Version | null, arma3?: Version | null, argo?: Version | null, };
