// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Call } from "./Call";
import type { Locality } from "./Locality";
import type { Param } from "./Param";
import type { Return } from "./Return";
import type { Since } from "./Since";

export type Syntax = { call: Call, ret: Return, left?: Param | null, right?: Param | null, since?: Since | null, effect?: Locality | null, };
